services:
  mongo:
    image: mongo:4.4
    container_name: songs_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    ports:
      - "5001:5001" 
    depends_on:
      - mongo
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production 
      - MONGO_URI=mongodb://mongo:27017/songs_db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/certs/cert.pem:ro
      - ./key.pem:/etc/nginx/certs/key.pem:ro
    ports:
      - "443:443" 
    depends_on:
      - web

volumes:
  mongo_data:



